// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Intercept place-order edge function calls to inject a fallback email when missing.
const originalInvoke = supabase.functions.invoke.bind(supabase.functions);
// @ts-ignore
supabase.functions.invoke = async function (functionName: string, options?: any) {
  if (functionName === 'place-order' && options?.body) {
    const body = options.body;
    if (!body.email) {
      const phone = body.shipping?.phone || 'guest';
      const cleanPhone = phone.trim().replace(/\s/g, '');
      body.email = `${cleanPhone || 'guest'}@khulnacart.com`;
    }
  }
  return originalInvoke(functionName, options);
};